FROM        centos/python-36-centos7

USER        root

WORKDIR     /ghmirror

COPY        . ./

RUN         pip install pipenv --upgrade
RUN         pipenv install --dev

ENTRYPOINT  ["make"]
CMD         ["check"]
