FROM        registry.access.redhat.com/ubi8/ubi-minimal

RUN         microdnf install python3.9 make && microdnf clean all
RUN         python3 -m pip install --no-cache-dir --upgrade pip setuptools

WORKDIR     /ghmirror

COPY        . ./

RUN         make develop

ENTRYPOINT  ["make"]
CMD         ["check"]
