apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/app-sre/github-mirror?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "master"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: github-mirror-master
    appstudio.openshift.io/component: github-mirror-master
    pipelines.appstudio.openshift.io/type: build
  name: github-mirror-master-on-pull-request
  namespace: app-sre-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/app-sre-tenant/github-mirror-master/github-mirror-master:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/app-sre/shared-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/multi-arch-build-pipeline.yaml
  taskRunTemplate: {}
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
