---
apiVersion: v1
kind: Template
metadata:
  name: github-mirror-acceptance
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${SERVICE_ACCOUNT}
  imagePullSecrets: "${{IMAGE_PULL_SECRETS}}"
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      ignore-check.kube-linter.io/unset-cpu-requirements: "no cpu limits"
    name: github-mirror-acceptance-${IMAGE_TAG}
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        serviceAccountName: ${SERVICE_ACCOUNT}
        containers:
          - image: ${IMAGE}:${IMAGE_TAG}
            imagePullPolicy: Always
            name: github-mirror-acceptance
            env:
              - name: GITHUB_MIRROR_URL
                value: ${GITHUB_MIRROR_URL}
              - name: CLIENT_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: ${CLIENT_TOKEN_SECRET}
                    key: CLIENT_TOKEN
            command:
              - python3
            args:
              - acceptance/test_basic.py
            resources:
              requests:
                memory: ${MEMORY_REQUESTS}
                cpu: ${CPU_REQUESTS}
              limits:
                memory: ${MEMORY_LIMIT}
parameters:
- name: IMAGE
  value: quay.io/app-sre/github-mirror
- name: IMAGE_TAG
  value: ''
  required: true
- name: GITHUB_MIRROR_URL
  value: ''
  required: true
- name: CLIENT_TOKEN_SECRET
  value: ''
  required: true
- name: SERVICE_ACCOUNT
  value: "github-mirror-acceptance"
  deplayName: github-mirror-acceptance service account
  description: name of the service account to use when deploying the pod
- name: MEMORY_REQUESTS
  value: 128Mi
- name: MEMORY_LIMIT
  value: 128Mi
- name: CPU_REQUESTS
  value: 100m
- name: IMAGE_PULL_SECRETS
  value: '[]'
